highlighter: rouge
permalink: /posts/:title
future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
url: http://www.thehackerwithin.org/illinois
name: Hacker Within
chapter: Illinois
description: The blog and site for THW at the U of I
twitter: hackerwithin_IL
gravatar_url: http://www.gravatar.com/avatar/0203c034a145af6cc2576d56cdb4cf73
disqus_username: hackerwithinadmin
relative_permalinks: false
